# Generated by Django 5.2.15 on 2026-07-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='course_syllabi/'),
        ),
    ]
